name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: |
          dotnet publish 'LL4AU.csproj' -r win-x64  -c Release -o "Build"
          7z a -tzip "Build-${{steps.version.outputs.prop}}.zip" "./Build/*"
          rm -r "Build"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Build*"
          tag_name: "1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
